
class GeoDataMargins:
    LV_CABLES_TO_MV_LV_STATION_MARGIN : float = 5.0
    LV_CABLES_TO_LV_STATION_MARGIN : float = 1.0
    MV_CABLES_TO_MV_LV_STATION_MARGIN : float = 3.0
    MV_CABLES_TO_HV_MV_STATION_MARGIN : float = 50.0
    MAX_DISTANCE_BUILDING_TO_LV_CABLE : float = 20.0

class LvCableConstants:
    ALLOWED_VOLTAGE_DROP_VOLT_PERCENTAGE : float = 17.0

class LoadSimoultaniousnessFactors:
    SIMOULTANIOUSNESS_FACTOR_10_HOUSEHOLDS : float = 0.59
    SIMOULTANIOUSNESS_FACTOR_50_HOUSEHOLDS : float = 0.49
    SIMOULTANIOUSNESS_FACTOR_100_HOUSEHOLDS : float = 0.46